export const TapasCardsData = [
  {
    name: "Grilled Potatoes",
    description: "Truffle aioli",
    image: "/assets/potatoes.webp",
    dietary: "Vegetarian | Gluten-Free",
    price: "7,50",
  },
  {
    name: "Beet Salad",
    description: "Spinach | fresh mint | lime | feta | pomegranate vinaigrette",
    image: "/assets/beetroot.webp",
    dietary: "Vegetarian | Gluten-Free",
    price: "7,50",
  },
  {
    name: "Carciofi",
    description: "Grilled | rocket & baby spinach | tomatoes | feta",
    image: "/assets/carciofi.webp",
    dietary: "Vegetarian | Gluten-Free",
    price: "8,50",
  },
  {
    name: "Goat Cheese",
    description: "Grilled | baby spinach | date-chilli jam | sesame seeds",
    image: "/assets/goat-cheese.webp",
    dietary: "Vegetarian | Gluten-Free",
    price: "8,50",
  },
  {
    name: "Burratina",
    description: "Tomatoes | rocket | olive oil | pomegranate vinaigrette",
    image: "/assets/burratina.webp",
    dietary: "Vegetarian | Gluten-Free",
    price: "10,50",
  },
  {
    name: "Avocado Tartare",
    description: "Fresh mint | lime juice | roasted pumpkin seeds",
    image: "/assets/Avocado-tatar.webp",
    dietary: "Vegetarian | Vegan | Gluten-Free",
    price: "11,50",
  },
  {
    name: "Scampi",
    description: "Pan-fried | tomatoes | chili | garlic | herbs",
    image: "/assets/scampi-chilli.webp",
    dietary: "Gluten-Free",
    price: "12,50",
  },
  {
    name: "Chicken Ratatouille",
    description: "Grilled chicken | ratatouille | yoghurt mint dip",
    image: "/assets/chicken-ratatouille.webp",
    dietary: "Gluten-Free",
    price: "11,00",
  },
  {
    name: "Grilled Chicken",
    description: "Marinated chicken | mushrooms | baby spinach | chili salsa",
    image: "/assets/chicken-chilli.webp",
    dietary: "Gluten-Free",
    price: "11,00",
  },
  {
    name: "Beef Tartare",
    description: "Hand-cut | capers | shallots | olive oil | soy sauce",
    image: "/assets/beef-tatar.webp",
    dietary: "Gluten-Free",
    price: "14,50",
  },
  {
    name: "Argentinian Beef",
    description: "Grilled Argentinian beef | rocket salad",
    image: "/assets/argentinian-beef.webp",
    dietary: "Gluten-Free",
    price: "14,50",
  },
  {
    name: "Pita Bread",
    description: "Choice of garlic, truffle or chili",
    image: "/assets/pita.webp",
    dietary: "Vegetarian",
    price: "2,50",
  },
];
